### this file is for testing the api
POST http://localhost:3000/api/groupingActivity
Content-Type: application/json

{
    "groupingActivityName": "測試組隊活動5",
    "isSupervised": true,
    "supervisorInvitationCode": "abcdefg",
    "invitationCode": "ghijk"
}
###
GET http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username":"billie",
    "password":"password"
}
###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username":"billie",
    "password":"password"
}
###
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Im5veWEiLCJpYXQiOjE2ODM2MTk2MTksImV4cCI6MTY4MzYxOTY0OX0.jSZAA7ImJeKR23X256iTdc81ObWzKn5Mcn_JbT29w7s
###
POST http://localhost:3000/api/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Im5veWEiLCJpYXQiOjE2ODM2MTk2MTksImV4cCI6MTY4MzYxOTY0OX0.jSZAA7ImJeKR23X256iTdc81ObWzKn5Mcn_JbT29w7s"
}


###
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "username":"noya",
    "password":"starbux",
    "passwordConfirmation":"starbux"
}
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username":"noya",
    "password":"starbux"
}
###